import { DB } from "./database.types"; // DB interface generated by Prisma
import { createPool } from "mysql2";
import { Kysely, MysqlDialect } from "kysely";

let db;

export function connectToDatabase(dbUrl: string | undefined) {
	if (!dbUrl) {
		console.error("Invalid DB_URL!");
		process.exit(1);
	}

	const connectionPool = createPool(dbUrl);

	const dialect = new MysqlDialect({
		pool: connectionPool,
	});

	db = new Kysely<DB>({ dialect });
}

export default db;
