import { DB } from "./database.types"; // DB interface generated by Prisma
import { createPool } from "mysql2";
import { Kysely, MysqlDialect } from "kysely";

let connection: Kysely<DB> | null = null;

export function connectToDatabase(dbUrl: string | undefined) {
	if (!dbUrl) {
		console.error("Invalid DB_URL!");
		process.exit(1);
	}

	const connectionPool = createPool(dbUrl);

	const dialect = new MysqlDialect({
		pool: connectionPool,
	});

	connection = new Kysely<DB>({ dialect });
}

export default function db() {
	if (!connection) {
		console.error("Can't access database!");
		process.exit(1);
	}

	return connection;
}
